<a href="https://colab.research.google.com/github/santhihubgit/My-Repository/blob/master/Interview_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+3

5

# 1. Assign a value to the variable and print the variable.

In [ ]:

# Creating variables

x=y=z="Variable"

print(x)
print(y)
print(z)


Variable
Variable
Variable


In [ ]:
b= x+y

print(b)


VariableVariable


In [ ]:
## Comparision operators -- "==","<",">",">=","<="
x= y==z
x

## These are called equality comparision operators

True

In [ ]:
x=y>=z
x

True

In [ ]:
a,b,c = 4.2,5,"Hello"

print(a)
print(b)
print(c)

4.2
5
Hello


In [ ]:
color_a ="Red"
color_b="Yellow"

print(color_a)
print(color_b)

Red
Yellow


In [ ]:
print(color_a,color_b)

Red Yellow


In [ ]:
color_c = color_a

print(color_a,color_b,color_c)

Red Yellow Red


# Create any array of at least 6 values. Using array slicing methods, print the 4th value.

In [ ]:
# creating array using zero method

import numpy as np

array= np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [ ]:
# creating array using ones method

a6 = np.ones(6)
a6

array([1., 1., 1., 1., 1., 1.])

In [ ]:
a1 = np.zeros((2,6))
a1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
a1 = np.ones((1,6))

a1

array([[1., 1., 1., 1., 1., 1.]])

In [ ]:
# creating array using linspace method function

x1 = np.linspace(1,10,10)
x1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Create any array of at least 6 values. Using array slicing methods, print the 4th value.

array = [10,20,30,40,50,60]

print(array[3])

40


# 3. Assign any string to a variable and reverse the string.

In [ ]:
## strings in python

## str

string1 = "Python Jupyter"

print(string1)



Python Jupyter


In [ ]:
print(string1[0])

P


In [ ]:
print(string1[4])

o


In [ ]:
print(string1[-1])

r


In [ ]:
print(string1[0:6])

Python


In [ ]:
print(string1[0:6:1])

Python


In [ ]:
print(string1[0:6:2])

Pto


In [ ]:
print(string1[0:6:3])

Ph


In [ ]:
a = "Python"
b= " Jupyter"
c = a+b

print(c)

Python Jupyter


In [ ]:
print("Python" + " Jupyer")

Python Jupyer


In [ ]:
print("Python", "Jupyter")

Python Jupyter


In [ ]:
print("Python Jupyer" *3)

Python JupyerPython JupyerPython Jupyer


# reverse string like pro

In [ ]:
string = "Python Jupyter"

print(string[::-1])

retypuJ nohtyP


In [ ]:
number = 123456

reverse_number = str(number)[::-1]

print(reverse_number)

TypeError: 'str' object is not callable

In [ ]:
number = 123456
print(str(number)[::-1])


TypeError: 'str' object is not callable

In [ ]:
rev_number = ''.join(reversed(str(number)))

print(rev_number)

TypeError: 'str' object is not callable

### *Explain the difference between list, tuple and dictionary*

*List*:
- A list is an ordered collection of items which is mutable (i.e., the items can be changed).
- Lists are defined using square brackets `[]`.
- Example: `my_list = [1, 2, 3, 4]`

*Tuple*:
- A tuple is an ordered collection of items which is immutable (i.e., the items cannot be changed once defined).
- Tuples are defined using parentheses `()`.
- Example: `my_tuple = (1, 2, 3, 4)`

*Dictionary*:
- A dictionary is an unordered collection of key-value pairs which is mutable.
- Dictionaries are defined using curly braces `{}`.
- Example: `my_dict = {'a': 1, 'b': 2, 'c': 3}`

In [ ]:
my_dict = {'a': 1, 'b': 2, 'c': 3}

my_dict

{'a': 1, 'b': 2, 'c': 3}

## *How do you handle missing values in pandas dataframe*

*It is a common task in data pre processing and data cleaning.*
*Firstly identify the missing values.*


In [ ]:
import pandas as pd

data = {
         'A': [1,2, None,4,5],
         'B': [None, 2,3,None,5],
         'C' : [1,None,3,4,None]
}

df =pd.DataFrame(data)
df





A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  3.0
3  4.0  NaN  4.0
4  5.0  5.0  NaN

In [ ]:
#Identifing missing values

print(df.isnull())

       A      B      C
0  False   True  False
1  False  False   True
2   True  False  False
3  False   True  False
4  False  False   True


In [ ]:
df.dropna()


Empty DataFrame
Columns: [A, B, C]
Index: []

In [ ]:
df


A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  3.0
3  4.0  NaN  4.0
4  5.0  5.0  NaN

In [ ]:
filled= df.fillna(0)

filled

A    B    C
0  1.0  0.0  1.0
1  2.0  2.0  0.0
2  0.0  3.0  3.0
3  4.0  0.0  4.0
4  5.0  5.0  0.0

# What are Lambda functions and where do we use them?

In [ ]:
add_1 = lambda x:x+1

Result = add_1(1)

print(Result)

2


In [ ]:
add_2 = lambda x,y:x+y

Res = add_2(1,7)  #passing 2 parameters x,y

Res

8

## MAP function

In [ ]:
my_numbers = [1,2,3,4,5,6,7,8]

def square(x):
    return x**2

squares = list(map(square, my_numbers))

squares

[1, 4, 9, 16, 25, 36, 49, 64]

In [ ]:
lambda_numbers = [1,2,3,4,5,6,7,8]

square_1 = list(map(lambda x:x**2, lambda_numbers))

square_1

[1, 4, 9, 16, 25, 36, 49, 64]